import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import {
  INVESTIGATION_SOURCE_ALLOCATION_POLICY,
  INVESTIGATION_SOURCE_RENDER_POLICY,
  SymbolLatticeService
} from "../../../src/application/index.js";
import { FileSystemSourceCatalog } from "../../../src/infrastructure/filesystem/index.js";
import { SqliteGraphStore } from "../../../src/infrastructure/sqlite/index.js";

const temporaryDirectories: string[] = [];

async function createProject(files: Readonly<Record<string, string>>): Promise<string> {
  const projectPath = await mkdtemp(resolve(tmpdir(), "symbol-lattice-context-allocation-"));
  temporaryDirectories.push(projectPath);
  await Promise.all(Object.entries(files).map(async ([filePath, sourceText]) => {
    const absolutePath = resolve(projectPath, ...filePath.split("/"));
    await mkdir(resolve(absolutePath, ".."), { recursive: true });
    await writeFile(absolutePath, sourceText, "utf8");
  }));
  return projectPath;
}

function longDeclaration(name: string, marker: string): string {
  return [
    `export function ${name}(): string {`,
    ...Array.from({ length: 90 }, (_value, index) =>
      `  const ${marker}${index} = "allocationProbe ${marker} ${index} ${"evidence ".repeat(6)}";`
    ),
    `  return ${marker}0;`,
    "}",
    ""
  ].join("\n");
}

function createService(): SymbolLatticeService {
  return new SymbolLatticeService(new SqliteGraphStore(), new FileSystemSourceCatalog());
}

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((directory) =>
    rm(directory, { recursive: true, force: true })
  ));
});

describe("generation-bound proportional investigation context", () => {
  it("shares one strict envelope across files and returns allocation receipts", async () => {
    const projectPath = await createProject({
      "src/primary.ts": longDeclaration("allocationProbePrimary", "primaryEvidence"),
      "src/secondary.ts": longDeclaration("allocationProbeSecondary", "secondaryEvidence"),
      "src/generated.ts": [
        "// Code generated by fixture. DO NOT EDIT.",
        longDeclaration("allocationProbeGenerated", "generatedEvidence")
      ].join("\n")
    });
    const service = createService();
    await service.init({ projectPath });

    const result = await service.investigate(projectPath, "allocationProbe", {
      searchLimit: 6,
      symbolLimit: 3,
      sourceCharacterBudget: 4_096
    });

    expect(result.bounds.declarationSource).toMatchObject({
      totalCharacterBudget: 4_096,
      minimumTotalCharacterBudget: 2_048,
      maximumTotalCharacterBudget: 64_000,
      allocationPolicy: INVESTIGATION_SOURCE_ALLOCATION_POLICY,
      renderPolicy: INVESTIGATION_SOURCE_RENDER_POLICY,
      requestedRenderMode: "adaptive"
    });
    expect(result.sourceAllocation).toMatchObject({
      policy: INVESTIGATION_SOURCE_ALLOCATION_POLICY,
      budget: { characterBudget: 4_096, minimumPerFile: 256 },
      summary: {
        candidateFileCount: 3,
        allocatedCharacters: 4_096,
        truncated: true
      }
    });
    expect(result.sourceAllocation.summary.emittedCharacters).toBeLessThan(4_096);
    expect(result.sourceAllocation.summary.unusedCharacters).toBe(
      4_096 - result.sourceAllocation.summary.emittedCharacters
    );
    expect(result.sourceAllocation.summary.reservedButNotEmittedCharacters).toBe(
      4_096 - result.sourceAllocation.summary.emittedCharacters
    );
    expect(result.sourceAllocation.files).toHaveLength(3);
    expect(
      result.sourceAllocation.files.reduce((total, file) => total + file.emittedCharacters, 0)
    ).toBe(result.sourceAllocation.summary.emittedCharacters);
    expect(result.declarations).toHaveLength(3);
    expect(
      result.declarations.reduce(
        (total, declaration) => total + (declaration.source?.text.length ?? 0),
        0
      )
    ).toBe(result.sourceAllocation.summary.emittedCharacters);
    expect(result.declarations.every((declaration) => declaration.allocation !== null)).toBe(true);
    expect(result.declarations.every((declaration) => declaration.source?.truncated === true)).toBe(true);
    expect(result.declarations.every((declaration) => declaration.render?.mode === "focused")).toBe(true);

    const generated = result.sourceAllocation.files.find(
      (file) => file.filePath === "src/generated.ts"
    );
    expect(generated).toMatchObject({
      generatedMultiplier: 0.25,
      reason: "generated-file-worth-penalty"
    });
    expect(generated?.allocatedCharacters).toBeGreaterThan(0);
    const handwrittenMinimum = Math.min(
      ...result.sourceAllocation.files
        .filter((file) => file.filePath !== "src/generated.ts")
        .map((file) => file.allocatedCharacters)
    );
    expect(generated!.allocatedCharacters).toBeLessThan(handwrittenMinimum);

    await expect(
      service.investigate(projectPath, "allocationProbe", { sourceCharacterBudget: 2_047 })
    ).rejects.toMatchObject({ code: "INVALID_INVESTIGATE_SOURCE_CHARACTER_BUDGET" });
    await expect(
      service.investigate(projectPath, "allocationProbe", { sourceCharacterBudget: 64_001 })
    ).rejects.toMatchObject({ code: "INVALID_INVESTIGATE_SOURCE_CHARACTER_BUDGET" });
  });

  it("returns all persisted declaration source and unused capacity when it fits", async () => {
    const projectPath = await createProject({
      "src/a.ts": "export function allocationProbeA(): number { return 1; }\n",
      "src/b.ts": "export function allocationProbeB(): number { return 2; }\n"
    });
    const service = createService();
    await service.init({ projectPath });

    const result = await service.investigate(projectPath, "allocationProbe", {
      symbolLimit: 2,
      sourceCharacterBudget: 2_048
    });

    expect(result.sourceAllocation.summary).toMatchObject({
      allocatedCharacters: result.sourceAllocation.summary.requestedCharacters,
      emittedCharacters: result.sourceAllocation.summary.requestedCharacters,
      truncated: false
    });
    expect(result.sourceAllocation.summary.unusedCharacters).toBeGreaterThan(0);
    expect(result.declarations.every((declaration) => declaration.source?.truncated === false)).toBe(true);
    expect(result.declarations.every((declaration) => declaration.render?.mode === "full")).toBe(true);
  });

  it("keeps a deep persisted lexical hit inside an adaptive contiguous slice", async () => {
    const lines = [
      "export function deepEvidenceTarget(): string {",
      ...Array.from({ length: 100 }, (_value, index) =>
        index === 72
          ? '  const answer = "needleAtThePersistedFocus";'
          : `  const padding${index} = "${"padding ".repeat(12)}";`
      ),
      "  return answer;",
      "}",
      ""
    ];
    const projectPath = await createProject({ "src/deep.ts": lines.join("\n") });
    const service = createService();
    await service.init({ projectPath });

    const result = await service.investigate(projectPath, "needleAtThePersistedFocus", {
      sourceCharacterBudget: 2_048,
      sourceRenderMode: "adaptive"
    });
    const declaration = result.declarations[0];

    expect(declaration?.source?.text).toContain("needleAtThePersistedFocus");
    expect(declaration?.render).toMatchObject({
      policy: INVESTIGATION_SOURCE_RENDER_POLICY,
      requestedMode: "adaptive",
      mode: "focused",
      contiguous: true,
      focus: { available: true, included: true, fallbackReason: null }
    });
    expect(declaration?.source?.renderedRange.start.line).toBeGreaterThan(1);
    expect(declaration?.source?.renderedCharacterOffsets.start).toBeGreaterThan(0);
    expect(declaration?.allocation?.emittedCharacters).toBe(declaration?.source?.text.length);
  });

  it("returns a proven signature with an explicit reservation receipt", async () => {
    const projectPath = await createProject({
      "src/signature.ts": [
        "export function signatureEvidence(",
        '  input: string = "literal { is not the body"',
        "): string {",
        ...Array.from({ length: 80 }, (_value, index) => `  const value${index} = input;`),
        "  return input;",
        "}",
        ""
      ].join("\n")
    });
    const service = createService();
    await service.init({ projectPath });

    const result = await service.investigate(projectPath, "signatureEvidence", {
      sourceCharacterBudget: 2_048,
      sourceRenderMode: "signature"
    });
    const declaration = result.declarations[0];

    expect(declaration?.source?.text).toBe([
      "export function signatureEvidence(",
      '  input: string = "literal { is not the body"',
      "): string"
    ].join("\n"));
    expect(declaration?.render).toMatchObject({
      requestedMode: "signature",
      mode: "signature",
      signature: { strategy: "brace-header", proven: true, fallbackReason: null }
    });
    expect(result.sourceAllocation.summary.reservedButNotEmittedCharacters).toBeGreaterThan(0);
    expect(result.sourceAllocation.summary.unusedCharacters).toBe(
      2_048 - result.sourceAllocation.summary.emittedCharacters
    );
  });

});
