import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import {
  INVESTIGATION_SOURCE_ALLOCATION_POLICY,
  SymbolLatticeService
} from "../../../src/application/index.js";
import { FileSystemSourceCatalog } from "../../../src/infrastructure/filesystem/index.js";
import { SqliteGraphStore } from "../../../src/infrastructure/sqlite/index.js";

const temporaryDirectories: string[] = [];

async function createProject(files: Readonly<Record<string, string>>): Promise<string> {
  const projectPath = await mkdtemp(resolve(tmpdir(), "symbol-lattice-context-allocation-"));
  temporaryDirectories.push(projectPath);
  await Promise.all(Object.entries(files).map(async ([filePath, sourceText]) => {
    const absolutePath = resolve(projectPath, ...filePath.split("/"));
    await mkdir(resolve(absolutePath, ".."), { recursive: true });
    await writeFile(absolutePath, sourceText, "utf8");
  }));
  return projectPath;
}

function longDeclaration(name: string, marker: string): string {
  return [
    `export function ${name}(): string {`,
    ...Array.from({ length: 90 }, (_value, index) =>
      `  const ${marker}${index} = "allocationProbe ${marker} ${index} ${"evidence ".repeat(6)}";`
    ),
    `  return ${marker}0;`,
    "}",
    ""
  ].join("\n");
}

function createService(): SymbolLatticeService {
  return new SymbolLatticeService(new SqliteGraphStore(), new FileSystemSourceCatalog());
}

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((directory) =>
    rm(directory, { recursive: true, force: true })
  ));
});

describe("generation-bound proportional investigation context", () => {
  it("shares one strict envelope across files and returns allocation receipts", async () => {
    const projectPath = await createProject({
      "src/primary.ts": longDeclaration("allocationProbePrimary", "primaryEvidence"),
      "src/secondary.ts": longDeclaration("allocationProbeSecondary", "secondaryEvidence"),
      "src/generated.ts": [
        "// Code generated by fixture. DO NOT EDIT.",
        longDeclaration("allocationProbeGenerated", "generatedEvidence")
      ].join("\n")
    });
    const service = createService();
    await service.init({ projectPath });

    const result = await service.investigate(projectPath, "allocationProbe", {
      searchLimit: 6,
      symbolLimit: 3,
      sourceCharacterBudget: 4_096
    });

    expect(result.bounds.declarationSource).toMatchObject({
      totalCharacterBudget: 4_096,
      minimumTotalCharacterBudget: 2_048,
      maximumTotalCharacterBudget: 64_000,
      allocationPolicy: INVESTIGATION_SOURCE_ALLOCATION_POLICY
    });
    expect(result.sourceAllocation).toMatchObject({
      policy: INVESTIGATION_SOURCE_ALLOCATION_POLICY,
      budget: { characterBudget: 4_096, minimumPerFile: 256 },
      summary: {
        candidateFileCount: 3,
        allocatedCharacters: 4_096,
        emittedCharacters: 4_096,
        unusedCharacters: 0,
        truncated: true
      }
    });
    expect(result.sourceAllocation.files).toHaveLength(3);
    expect(
      result.sourceAllocation.files.reduce((total, file) => total + file.emittedCharacters, 0)
    ).toBe(4_096);
    expect(result.declarations).toHaveLength(3);
    expect(
      result.declarations.reduce(
        (total, declaration) => total + (declaration.source?.text.length ?? 0),
        0
      )
    ).toBe(4_096);
    expect(result.declarations.every((declaration) => declaration.allocation !== null)).toBe(true);
    expect(result.declarations.every((declaration) => declaration.source?.truncated === true)).toBe(true);

    const generated = result.sourceAllocation.files.find(
      (file) => file.filePath === "src/generated.ts"
    );
    expect(generated).toMatchObject({
      generatedMultiplier: 0.25,
      reason: "generated-file-worth-penalty"
    });
    expect(generated?.allocatedCharacters).toBeGreaterThan(0);
    const handwrittenMinimum = Math.min(
      ...result.sourceAllocation.files
        .filter((file) => file.filePath !== "src/generated.ts")
        .map((file) => file.allocatedCharacters)
    );
    expect(generated!.allocatedCharacters).toBeLessThan(handwrittenMinimum);

    await expect(
      service.investigate(projectPath, "allocationProbe", { sourceCharacterBudget: 2_047 })
    ).rejects.toMatchObject({ code: "INVALID_INVESTIGATE_SOURCE_CHARACTER_BUDGET" });
    await expect(
      service.investigate(projectPath, "allocationProbe", { sourceCharacterBudget: 64_001 })
    ).rejects.toMatchObject({ code: "INVALID_INVESTIGATE_SOURCE_CHARACTER_BUDGET" });
  });

  it("returns all persisted declaration source and unused capacity when it fits", async () => {
    const projectPath = await createProject({
      "src/a.ts": "export function allocationProbeA(): number { return 1; }\n",
      "src/b.ts": "export function allocationProbeB(): number { return 2; }\n"
    });
    const service = createService();
    await service.init({ projectPath });

    const result = await service.investigate(projectPath, "allocationProbe", {
      symbolLimit: 2,
      sourceCharacterBudget: 2_048
    });

    expect(result.sourceAllocation.summary).toMatchObject({
      allocatedCharacters: result.sourceAllocation.summary.requestedCharacters,
      emittedCharacters: result.sourceAllocation.summary.requestedCharacters,
      truncated: false
    });
    expect(result.sourceAllocation.summary.unusedCharacters).toBeGreaterThan(0);
    expect(result.declarations.every((declaration) => declaration.source?.truncated === false)).toBe(true);
  });

});
