import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import { SymbolLatticeService } from "../../../src/application/index.js";
import { GENERATED_FILE_CLASSIFIER_VERSION } from "../../../src/domain/index.js";
import { FileSystemSourceCatalog } from "../../../src/infrastructure/filesystem/index.js";
import { SqliteGraphStore } from "../../../src/infrastructure/sqlite/index.js";

const temporaryDirectories: string[] = [];

async function createProject(files: Readonly<Record<string, string>>): Promise<string> {
  const projectPath = await mkdtemp(resolve(tmpdir(), "SymbolLattice-generated-"));
  temporaryDirectories.push(projectPath);
  await Promise.all(Object.entries(files).map(async ([filePath, sourceText]) => {
    const absolutePath = resolve(projectPath, ...filePath.split("/"));
    await mkdir(resolve(absolutePath, ".."), { recursive: true });
    await writeFile(absolutePath, sourceText, "utf8");
  }));
  return projectPath;
}

function createService(): SymbolLatticeService {
  return new SymbolLatticeService(new SqliteGraphStore(), new FileSystemSourceCatalog());
}

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((directory) =>
    rm(directory, { recursive: true, force: true })
  ));
});

describe("generation-bound generated-file intelligence", () => {
  it("persists evidence, soft-ranks every query surface, and discloses the decision", async () => {
    const projectPath = await createProject({
      "src/target.ts": [
        "export function sharedTarget(): void {}"
      ].join("\n"),
      "src/generated-target.ts": [
        "// Code generated by fixture. DO NOT EDIT.",
        "export function generatedCallee(): void {}"
      ].join("\n"),
      "src/workflow-target.ts": "export function workflowCallee(): void {}\n",
      "src/generated.ts": [
        "// Code generated by fixture. DO NOT EDIT.",
        "import { sharedTarget } from './target.js';",
        "export function ProcessPayroll(): void { sharedTarget(); }"
      ].join("\n"),
      "src/workflow.ts": [
        `// ${"ordinary context ".repeat(200)}`,
        "import { sharedTarget } from './target.js';",
        "export function ProcessPayroll(): void { sharedTarget(); }"
      ].join("\n"),
      "src/orchestrator.ts": [
        "import { generatedCallee } from './generated-target.js';",
        "import { workflowCallee } from './workflow-target.js';",
        "export function orchestrate(): void { generatedCallee(); workflowCallee(); }"
      ].join("\n")
    });
    const service = createService();
    await service.init({ projectPath });

    const files = await service.files(projectPath, { limit: 10 });
    const generatedFile = files.files.find((file) => file.filePath === "src/generated.ts");
    expect(generatedFile?.generated).toEqual({
      classifierVersion: GENERATED_FILE_CLASSIFIER_VERSION,
      generated: true,
      evidence: [
        {
          kind: "header",
          ruleId: "generated.header.code-generated-do-not-edit",
          range: {
            start: { line: 1, column: 4 },
            end: { line: 1, column: 43 }
          }
        }
      ]
    });

    const search = await service.search(projectPath, "ProcessPayroll", { limit: 2 });
    expect(search.results.map((item) => item.filePath)).toEqual([
      "src/workflow.ts",
      "src/generated.ts"
    ]);
    expect(search.ranking).toMatchObject({
      policy: "generated-soft-rank-v1",
      classifierVersion: GENERATED_FILE_CLASSIFIER_VERSION,
      requestedLimit: 2,
      returnedCount: 2
    });
    expect(search.results.map((item) => item.ranking)).toEqual([
      {
        retrievalRank: 2,
        finalRank: 1,
        generatedPenalty: 0,
        reason: "handwritten-preferred"
      },
      {
        retrievalRank: 1,
        finalRank: 2,
        generatedPenalty: 1,
        reason: "generated-file-soft-penalty"
      }
    ]);

    const find = await service.find(projectPath, "ProcessPayroll", { limit: 2 });
    expect(find.symbols.map((symbol) => symbol.filePath)).toEqual([
      "src/workflow.ts",
      "src/generated.ts"
    ]);
    expect(find.ranking.items.map((item) => ({
      filePath: item.filePath,
      baseRank: item.baseRank,
      finalRank: item.finalRank,
      generatedPenalty: item.generatedPenalty
    }))).toEqual([
      { filePath: "src/workflow.ts", baseRank: 2, finalRank: 1, generatedPenalty: 0 },
      { filePath: "src/generated.ts", baseRank: 1, finalRank: 2, generatedPenalty: 1 }
    ]);

    const investigate = await service.investigate(projectPath, "ProcessPayroll", {
      searchLimit: 2,
      symbolLimit: 2
    });
    expect(investigate.selection.items.map((item) => item.symbol.filePath)).toEqual([
      "src/workflow.ts",
      "src/generated.ts"
    ]);
    expect(investigate.selection.items.map((item) => item.generatedRanking.generatedPenalty))
      .toEqual([0, 1]);

    const target = find.symbols.find((symbol) => symbol.name === "ProcessPayroll");
    expect(target).toBeDefined();
    const sharedTarget = (await service.find(projectPath, "sharedTarget", { limit: 1 })).symbols[0];
    expect(sharedTarget).toBeDefined();
    const callers = await service.callers(projectPath, sharedTarget!.qualifiedName);
    expect(callers.relations.map((relation) => relation.symbol.filePath)).toEqual([
      "src/workflow.ts",
      "src/generated.ts"
    ]);
    expect(callers.ranking.items.map((item) => item.generatedPenalty)).toEqual([0, 1]);

    const orchestrate = (await service.find(projectPath, "orchestrate", { limit: 1 })).symbols[0];
    expect(orchestrate).toBeDefined();
    const callees = await service.callees(projectPath, orchestrate!.qualifiedName);
    expect(callees.relations.map((relation) => relation.symbol.name)).toEqual([
      "workflowCallee",
      "generatedCallee"
    ]);
    expect(callees.ranking.items.map((item) => item.generatedPenalty)).toEqual([0, 1]);

    const reopened = createService();
    const persistedFiles = await reopened.files(projectPath, { limit: 10 });
    expect(persistedFiles.files.find((file) => file.filePath === "src/generated.ts")?.generated)
      .toEqual(generatedFile?.generated);
  });

  it("never filters an all-generated result set", async () => {
    const projectPath = await createProject({
      "src/a.generated.ts": "export function GeneratedOnly(): void {}\n",
      "src/b.generated.ts": "export function GeneratedOnly(): void {}\n"
    });
    const service = createService();
    await service.init({ projectPath });

    const result = await service.search(projectPath, "GeneratedOnly", { limit: 2 });
    expect(result.results).toHaveLength(2);
    expect(result.results.every((item) => item.generated.generated)).toBe(true);
    expect(result.results.map((item) => item.ranking.finalRank)).toEqual([1, 2]);
  });
});
