import type { SourceRange } from "./types.js";

/** Changes whenever a path or header rule changes the persisted verdict. */
export const GENERATED_FILE_CLASSIFIER_VERSION = "generated-evidence-v1";

export interface GeneratedFileEvidence {
  readonly kind: "path" | "header";
  readonly ruleId: string;
  /** Header evidence uses the graph's one-based, end-exclusive source convention. */
  readonly range: SourceRange | null;
}

/** Immutable, generation-bound classification saved with one indexed file. */
export interface GeneratedFileClassification {
  readonly classifierVersion: string;
  readonly generated: boolean;
  readonly evidence: readonly GeneratedFileEvidence[];
}

interface PathRule {
  readonly ruleId: string;
  readonly pattern: RegExp;
}

interface HeaderRule {
  readonly ruleId: string;
  readonly pattern: RegExp;
}

const PATH_RULES: readonly PathRule[] = [
  { ruleId: "generated.path.go.grpc-protobuf", pattern: /_grpc\.pb\.go$/iu },
  { ruleId: "generated.path.go.protobuf", pattern: /\.pb\.go$/iu },
  { ruleId: "generated.path.go.mock", pattern: /(?:^|\/)(?:mock_[^/]+|[^/]+_mocks?)\.go$/iu },
  { ruleId: "generated.path.javascript.generated-suffix", pattern: /\.(?:generated|gen)\.[cm]?[jt]sx?$/iu },
  { ruleId: "generated.path.javascript.protobuf", pattern: /(?:\.pb|_grpc_pb|_pb)\.[cm]?js$/iu },
  { ruleId: "generated.path.javascript.minified", pattern: /\.min\.[cm]?js$/iu },
  { ruleId: "generated.path.python.protobuf", pattern: /_pb2(?:_grpc)?\.pyi?$/iu },
  { ruleId: "generated.path.cpp.protobuf", pattern: /\.pb\.(?:cc|h|hpp)$/iu },
  { ruleId: "generated.path.dotnet.generated", pattern: /(?:\.g|\.designer)\.cs$/iu },
  { ruleId: "generated.path.java.grpc", pattern: /(?:Grpc|OuterClass)\.java$/u },
  { ruleId: "generated.path.swift.protobuf", pattern: /\.pb\.swift$/iu },
  { ruleId: "generated.path.dart.codegen", pattern: /\.(?:g|freezed|pb|pbgrpc|chopper)\.dart$/iu },
  { ruleId: "generated.path.rust.generated", pattern: /\.(?:generated|gen)\.rs$/iu }
];

const HEADER_RULES: readonly HeaderRule[] = [
  {
    ruleId: "generated.header.code-generated-do-not-edit",
    pattern: /\bcode\s+generated\b.{0,200}?\bdo\s+not\s+(?:edit|modify|change)\b[.!]?/iu
  },
  {
    ruleId: "generated.header.tool-generated-do-not-edit",
    pattern: /\b(?:auto[- ]?generated|automatically\s+generated|autogenerated)\s+(?:by|from|with)\b.{0,200}?\bdo\s+not\s+(?:edit|modify|change)\b[.!]?/iu
  },
  {
    ruleId: "generated.header.generated-tag",
    pattern: /(?:^|[^\p{L}\p{N}_@])@generated\b/u
  },
  {
    ruleId: "generated.header.dotnet-auto-generated",
    pattern: /<auto-?generated\s*\/?>/iu
  },
  {
    ruleId: "generated.header.named-generator",
    pattern: /\b(?:automatically\s+generated|auto[- ]?generated|autogenerated)\s+by\b/iu
  },
  {
    ruleId: "generated.header.self-declaration",
    pattern: /\bthis\s+(?:file|class|code|module)\s+(?:is|was)\s+(?:auto[- ]?)?generated\b/iu
  },
  {
    ruleId: "generated.header.reverse-do-not-edit",
    pattern: /\bdo\s+not\s+(?:edit|modify)\b.{0,120}?\b(?:auto[- ]?generated|generated\s+(?:file|code))\b/iu
  }
];

const HEADER_CHARACTER_LIMIT = 8_192;
const HEADER_LINE_LIMIT = 60;

interface CommentState {
  readonly close: string;
}

/** Precision-first classification; it never excludes the file from the graph. */
export function classifyGeneratedFile(
  filePath: string,
  sourceText: string
): GeneratedFileClassification {
  const normalizedPath = filePath.replaceAll("\\", "/");
  const evidence: GeneratedFileEvidence[] = [];

  for (const rule of PATH_RULES) {
    if (rule.pattern.test(normalizedPath)) {
      evidence.push({ kind: "path", ruleId: rule.ruleId, range: null });
      break;
    }
  }

  const headerEvidence = classifyGeneratedHeader(sourceText);
  if (headerEvidence !== null) {
    evidence.push(headerEvidence);
  }

  return {
    classifierVersion: GENERATED_FILE_CLASSIFIER_VERSION,
    generated: evidence.length > 0,
    evidence
  };
}

/** Backwards-compatible read for snapshots created before generated evidence existed. */
export function generatedClassificationFor(
  value: { readonly generated?: GeneratedFileClassification }
): GeneratedFileClassification {
  return value.generated ?? {
    classifierVersion: "unclassified-legacy-snapshot",
    generated: false,
    evidence: []
  };
}

function classifyGeneratedHeader(sourceText: string): GeneratedFileEvidence | null {
  if (sourceText.length === 0) {
    return null;
  }
  const header = sourceText.slice(0, HEADER_CHARACTER_LIMIT);
  if (!/generat/iu.test(header)) {
    return null;
  }

  const lines = header.split(/\r\n|\r|\n/u).slice(0, HEADER_LINE_LIMIT);
  let commentState: CommentState | null = null;
  for (const [lineIndex, line] of lines.entries()) {
    const comment = commentContent(line, commentState);
    commentState = comment.nextState;
    if (comment.content === null) {
      continue;
    }
    for (const rule of HEADER_RULES) {
      const match = rule.pattern.exec(comment.content.text);
      if (match === null) {
        continue;
      }
      const matchedText = match[0].startsWith(" ") ? match[0].slice(1) : match[0];
      const leadingAdjustment = match[0].length - matchedText.length;
      const startOffset = comment.content.offset + match.index + leadingAdjustment;
      return {
        kind: "header",
        ruleId: rule.ruleId,
        range: {
          start: { line: lineIndex + 1, column: startOffset + 1 },
          end: { line: lineIndex + 1, column: startOffset + matchedText.length + 1 }
        }
      };
    }
  }
  return null;
}

function commentContent(
  line: string,
  state: CommentState | null
): {
  readonly content: { readonly text: string; readonly offset: number } | null;
  readonly nextState: CommentState | null;
} {
  if (state !== null) {
    const closeIndex = line.indexOf(state.close);
    return {
      content: { text: closeIndex < 0 ? line : line.slice(0, closeIndex), offset: 0 },
      nextState: closeIndex < 0 ? state : null
    };
  }

  const lineComment = /^(\s*(?:\/\/|#|--|%|;|'|!|\*+)\s?)(.*)$/u.exec(line);
  if (lineComment !== null) {
    return {
      content: { text: lineComment[2] ?? "", offset: lineComment[1]?.length ?? 0 },
      nextState: null
    };
  }

  const blockOpeners: readonly { readonly open: string; readonly close: string }[] = [
    { open: "/*", close: "*/" },
    { open: "<!--", close: "-->" },
    { open: "(*", close: "*)" },
    { open: "{-", close: "-}" },
    { open: '"""', close: '"""' },
    { open: "'''", close: "'''" },
    { open: "<#", close: "#>" }
  ];
  const leadingWhitespace = line.length - line.trimStart().length;
  for (const delimiter of blockOpeners) {
    if (!line.startsWith(delimiter.open, leadingWhitespace)) {
      continue;
    }
    const contentStart = leadingWhitespace + delimiter.open.length;
    const closeIndex = line.indexOf(delimiter.close, contentStart);
    return {
      content: {
        text: closeIndex < 0 ? line.slice(contentStart) : line.slice(contentStart, closeIndex),
        offset: contentStart
      },
      nextState: closeIndex < 0 ? { close: delimiter.close } : null
    };
  }
  return { content: null, nextState: null };
}
