import { describe, expect, it } from "vitest";

import {
  GENERATED_FILE_CLASSIFIER_VERSION,
  classifyGeneratedFile
} from "../../../src/domain/index.js";

describe("generated-file classification", () => {
  it("retains a precise path-rule receipt without reading source semantics", () => {
    const classification = classifyGeneratedFile(
      "internal/api/user_grpc.pb.go",
      "package api\n"
    );

    expect(classification).toEqual({
      classifierVersion: GENERATED_FILE_CLASSIFIER_VERSION,
      generated: true,
      evidence: [
        {
          kind: "path",
          ruleId: "generated.path.go.grpc-protobuf",
          range: null
        }
      ]
    });
  });

  it("retains the exact header range for an ordinary generated filename", () => {
    const classification = classifyGeneratedFile(
      "internal/gen/payroll/store.go",
      [
        "// Copyright Example",
        "// Code generated by fkit. DO NOT EDIT.",
        "package payroll"
      ].join("\n")
    );

    expect(classification.generated).toBe(true);
    expect(classification.evidence).toEqual([
      {
        kind: "header",
        ruleId: "generated.header.code-generated-do-not-edit",
        range: {
          start: { line: 2, column: 4 },
          end: { line: 2, column: 40 }
        }
      }
    ]);
  });

  it("rejects marker-like strings, body prose, and ambiguous generation claims", () => {
    expect(classifyGeneratedFile(
      "src/generator.ts",
      [
        "export const banner = \"Code generated by us. DO NOT EDIT.\";",
        ...Array.from({ length: 70 }, (_, index) => `// ordinary ${index}`),
        "// Code generated by a late tool. DO NOT EDIT."
      ].join("\n")
    ).generated).toBe(false);

    expect(classifyGeneratedFile(
      "src/report.ts",
      "// This table is automatically generated at runtime.\nexport const report = true;\n"
    ).generated).toBe(false);
  });

  it("keeps independent path and header evidence in deterministic order", () => {
    const classification = classifyGeneratedFile(
      "src/client.generated.ts",
      "/* @generated */\nexport const client = true;\n"
    );

    expect(classification.evidence.map((item) => [item.kind, item.ruleId])).toEqual([
      ["path", "generated.path.javascript.generated-suffix"],
      ["header", "generated.header.generated-tag"]
    ]);
  });
});
