/* Generated by scripts/build/generate-go-parser.mjs from @lezer/go 1.0.1.
 * Local grammar change: optional range-clause left-hand binding.
 * Regenerate instead of editing this file.

MIT License

Copyright (C) 2020 by Marijn Haverbeke <marijn@haverbeke.berlin> and others

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

*/
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  insertedSemi = 177,
  space = 179,
  LineComment = 1,
  BlockComment = 2,
  SourceFile = 3,
  PackageClause = 4,
  identifier = 184,
  _package = 5,
  DefName = 6,
  ImportDecl = 8,
  _import = 9,
  ImportSpec = 10,
  String = 12,
  closeParen = 13,
  Number = 17,
  Rune = 20,
  VariableName = 21,
  struct = 24,
  closeBrace = 25,
  FieldDecl = 28,
  FieldName = 29,
  star = 32,
  func = 34,
  Parameters = 35,
  Parameter = 36,
  _interface = 39,
  MethodElem = 41,
  chan = 47,
  TypeName = 51,
  ParameterizedType = 52,
  closeBracket = 53,
  TypeArgs = 55,
  map = 59,
  LiteralValue = 60,
  Block = 68,
  SelectorExpr = 70,
  ParameterizedExpr = 75,
  Arguments = 76,
  make = 78,
  _new = 79,
  newArguments = 80,
  CompareOp = 90,
  SendStatement = 93,
  IncDecOp = 95,
  UpdateOp = 98,
  shortVarDecl = 99,
  ConstDecl = 101,
  _const = 102,
  ConstSpec = 103,
  TypeDecl = 105,
  type = 106,
  TypeSpec = 107,
  TypeParams = 108,
  TypeParam = 109,
  VarDecl = 111,
  _var = 112,
  VarSpec = 113,
  LabelName = 116,
  IfStatement = 117,
  _if = 118,
  _else = 119,
  _switch = 121,
  SwitchBlock = 122,
  _case = 124,
  _default = 125,
  typeSwitchBlock = 127,
  _for = 130,
  ForClause = 131,
  RangeClause = 132,
  range = 133,
  go = 135,
  select = 137,
  ReceiveStatement = 140,
  _return = 142,
  _break = 144,
  _continue = 145,
  goto = 146,
  fallthrough = 148,
  defer = 150,
  FunctionDecl = 151,
  MethodDecl = 152
