export const AUTOMATIC_PROJECT_INDEX_GUIDANCE = `- When the current work is inside a recognized software repository and the task requires locating, understanding, or changing source code, run \`SymbolLattice status . --json\` from the resolved repository root before broad file exploration.
- Resolve repository topology before indexing. A directory governed by one outer \`.git\` root is a monorepo even when it contains multiple packages or project manifests; initialize that outer repository once. A directory whose child projects have separate \`.git\` roots, or distinct manifest roots not governed by one outer \`.git\`, is a workspace container and is not itself a repository.
- Recognize an individual software repository only when its resolved root contains \`.git\`, a recognized project manifest, or supported source files. Use that resolved root rather than whichever nested directory happens to be current.
- When the current path is a workspace container, discover candidate repository roots with a bounded pass over declared workspace members and child directories at most two levels deep. Skip hidden metadata, dependencies, generated output, caches, archives, and temporary directories; do not perform an unbounded recursive crawl.
- If the task concerns one repository, initialize only that repository. If the user asks about the whole workspace or multiple repositories, initialize each relevant repository separately and never initialize the workspace container. For every missing \`.SymbolLattice/index.sqlite\`, run \`SymbolLattice init .\` automatically from that repository's resolved root before broad exploration. The user does not need to request indexing separately. Briefly tell the user which local indexes are being created because initial indexing can take time and disk space.
- Never initialize a filesystem root, home directory, Desktop root, temporary directory, dependency directory, generated-output directory, or a parent directory that contains multiple unrelated projects.
- For a whole-workspace question, query every relevant repository index separately, pass its own \`projectPath\` on each SymbolLattice call, and combine the project-scoped findings in the answer. Do not infer cross-repository edges or present the combined result as one graph.
- If automatic initialization fails or cannot be performed, report the reason once and fall back to targeted \`rg\` and direct file reads. Never run \`index\` or rebuild an existing index unless the user explicitly requests it.`;

export const SYMBOL_LATTICE_MCP_INSTRUCTIONS = `SymbolLattice provides a local source-code graph for coding agents. Its MCP tools are read-only and query an existing project index.

${AUTOMATIC_PROJECT_INDEX_GUIDANCE}

When an index is available, use \`SymbolLattice_explore\` before grep, find, or broad file reads for code discovery. Prefer narrower SymbolLattice tools for exact source, impact, affected tests, or generation history. Treat pending, unresolved, ambiguous, truncated, or low-confidence results as incomplete evidence. Do not edit or commit files inside \`.SymbolLattice\`.`;
